[mgr]
show_hidden = true
sort_by = "natural"
sort_dir_first = true

[preview]
max_width = 1000
max_height = 1000

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "code" },
]
