# ~/.config/hypr/hypridle.conf

general {
    ignore_dbus_inhibit = false   # <-- respeta el inhibit (Waybar/portales)
    # opcional:
    # lock_cmd = "pidof hyprlock || hyprlock"
}

# Bloquear a los 5 minutos
listener {
    timeout = 300
    on-timeout = hyprlock
    on-resume  = /run/current-system/sw/bin/notify-send Desbloqueado
}

# Apagar pantalla a los 6 minutos
listener {
    timeout = 360
    on-timeout = /run/current-system/sw/bin/hyprctl dispatch dpms off
    on-resume  = /run/current-system/sw/bin/hyprctl dispatch dpms on
}
